USE MASTER
GO
-- Kiểm tra xem cơ sở dữ liệu 'SFCM' đã tồn tại chưa
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'SFCM')
BEGIN
    -- Nếu tồn tại, thì xóa cơ sở dữ liệu 'SFCM'
    DROP DATABASE SFCM
END
-- Tạo mới cơ sở dữ liệu 'SFCM'
GO
CREATE DATABASE SFCM

-- Sử dụng cơ sở dữ liệu 'SFCM' để tạo các bảng
GO
USE SFCM
GO

USE [SFCM]
GO

/****** Object:  Table [dbo].[BS_CUSTOMER]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_CUSTOMER](
	[CUSTOMER_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_TYPE_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_NAME] [nvarchar](500) NOT NULL,
	[ADDRESS] [nvarchar](max) NOT NULL,
	[TAX_CODE] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](max) NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
	[USERNAME] [nvarchar](450) NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [BS_CUSTOMER_UNIQUE] UNIQUE NONCLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [dbo].[thach_table]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create view [dbo].[thach_table] AS
select CUSTOMER_CODE, CUSTOMER_NAME 
from BS_CUSTOMER
GO
/****** Object:  Table [dbo].[BS_BLOCK]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_BLOCK](
	[BLOCK_CODE] [nvarchar](10) NOT NULL,
	[BLOCK_NAME] [nvarchar](250) NOT NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NOT NULL,
	[TIER_COUNT] [int] NOT NULL,
	[SLOT_COUNT] [int] NOT NULL,
	[BLOCK_LENGTH] [numeric](10, 2) NOT NULL,
	[BLOCK_WIDTH] [numeric](10, 2) NOT NULL,
	[BLOCK_HEIGHT] [numeric](10, 2) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BLOCK_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_CELL]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_CELL](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[BLOCK_CODE] [nvarchar](10) NOT NULL,
	[TIER_ORDERED] [int] NULL,
	[SLOT_ORDERED] [int] NULL,
	[STATUS] [int] NOT NULL,
	[CELL_LENGTH] [numeric](10, 2) NOT NULL,
	[CELL_WIDTH] [numeric](10, 2) NOT NULL,
	[CELL_HEIGHT] [numeric](10, 2) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_CUSTOMER_TYPE]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_CUSTOMER_TYPE](
	[CUSTOMER_TYPE_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_TYPE_NAME] [nvarchar](500) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_ITEM_TYPE]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_ITEM_TYPE](
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[ITEM_TYPE_NAME] [nvarchar](500) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ITEM_TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_METHOD]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_METHOD](
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[METHOD_NAME] [nvarchar](500) NOT NULL,
	[IS_IN_OUT] [char](1) NOT NULL,
	[IS_SERVICE] [bit] NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[METHOD_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_PACKAGE_UNIT]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_PACKAGE_UNIT](
	[PACKAGE_UNIT_CODE] [nvarchar](50) NOT NULL,
	[PACKAGE_UNIT_NAME] [nvarchar](500) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PACKAGE_UNIT_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_WAREHOUSE]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_WAREHOUSE](
	[WAREHOUSE_CODE] [nvarchar](50) NOT NULL,
	[WAREHOUSE_NAME] [nvarchar](500) NOT NULL,
	[ACREAGE] [numeric](18, 3) NULL,
	[STATUS] [bit] NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WAREHOUSE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIG_ATTACH_SRV]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIG_ATTACH_SRV](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[ATTACH_SERVICE_CODE] [nvarchar](50) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DELIVER_ORDER]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DELIVER_ORDER](
	[DE_ORDER_NO] [nvarchar](50) NOT NULL,
	[CUSTOMER_CODE] [nvarchar](50) NOT NULL,
	[CONTAINER_ID] [uniqueidentifier] NULL,
	[PACKAGE_ID] [uniqueidentifier] NULL,
	[INV_ID] [nvarchar](20) NULL,
	[INV_DRAFT_ID] [nvarchar](20) NULL,
	[ISSUE_DATE] [datetime] NOT NULL,
	[EXP_DATE] [datetime] NOT NULL,
	[TOTAL_CBM] [decimal](10, 3) NULL,
	[JOB_CHK] [bit] NULL,
	[NOTE] [nvarchar](max) NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
	[IS_VALID] [bit] NULL,
	[CAN_CANCEL] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[DE_ORDER_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DELIVERY_ORDER_DETAIL]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DELIVERY_ORDER_DETAIL](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[DE_ORDER_NO] [nvarchar](50) NOT NULL,
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[CBM] [decimal](10, 3) NULL,
	[LOT_NO] [int] NULL,
	[QUANTITY_CHK] [bit] NOT NULL,
	[REF_PAKAGE] [uniqueidentifier] NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_CNTR_MNF_LD]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_CNTR_MNF_LD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[BILLOFLADING] [varchar](50) NULL,
	[SEALNO] [nvarchar](35) NULL,
	[CNTRNO] [varchar](11) NOT NULL,
	[CNTRSZTP] [varchar](5) NOT NULL,
	[STATUSOFGOOD] [bit] NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NULL,
	[CONSIGNEE] [nvarchar](50) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_PACKAGE_MNF_LD]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_PACKAGE_MNF_LD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[PACKAGE_UNIT_CODE] [nvarchar](50) NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[CONTAINER_ID] [uniqueidentifier] NOT NULL,
	[HOUSE_BILL] [nvarchar](200) NOT NULL,
	[CARGO_PIECE] [int] NULL,
	[CBM] [decimal](10, 3) NOT NULL,
	[DECLARE_NO] [varchar](max) NULL,
	[NOTE] [nvarchar](max) NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
	[JOB_TYPE ] [nvarchar](10) NOT NULL,
	[TIME_IN] [datetime] NULL,
	[TIME_OUT] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_PALLET_STOCK]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_PALLET_STOCK](
	[PALLET_NO] [nvarchar](100) NOT NULL,
	[JOB_QUANTITY_ID] [uniqueidentifier] NOT NULL,
	[CELL_ID] [uniqueidentifier] NULL,
	[PALLET_STATUS] [char](1) NULL,
	[PALLET_LENGTH] [numeric](10, 2) NULL,
	[PALLET_WIDTH] [numeric](10, 2) NULL,
	[PALLET_HEIGHT] [numeric](10, 2) NULL,
	[NOTE] [nvarchar](max) NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PALLET_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_VESSEL_VISIT]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_VESSEL_VISIT](
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[VESSEL_NAME] [nvarchar](200) NOT NULL,
	[INBOUND_VOYAGE] [varchar](20) NOT NULL,
	[ETA] [datetime] NOT NULL,
	[CallSign] [varchar](50) NULL,
	[IMO] [varchar](30) NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[VOYAGEKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_VAT]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_VAT](
	[INV_NO] [nvarchar](20) NOT NULL,
	[INV_DATE] [datetime] NULL,
	[PAYER] [nvarchar](20) NULL,
	[AMOUNT] [numeric](12, 2) NULL,
	[VAT] [numeric](12, 2) NULL,
	[TAMOUNT] [numeric](12, 2) NULL,
	[PAYMENT_STATUS] [nvarchar](1) NULL,
	[ACC_CD] [nvarchar](10) NULL,
	[CANCEL_DATE] [datetime] NULL,
	[CANCLE_REMARK] [nvarchar](200) NULL,
	[CANCLE_BY] [nvarchar](25) NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[INV_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_VAT_DTL]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_VAT_DTL](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[TRF_DESC] [nvarchar](500) NULL,
	[CARGO_TYPE] [nvarchar](10) NULL,
	[QTY] [numeric](12, 2) NULL,
	[UNIT_RATE] [numeric](15, 5) NULL,
	[AMOUNT] [numeric](12, 2) NULL,
	[VAT_RATE] [numeric](5, 2) NULL,
	[VAT] [numeric](12, 2) NULL,
	[TAMOUNT] [numeric](12, 2) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](50) NULL,
	[UPDATED_AT] [datetime] NOT NULL,
	[INV_ID] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_QUANTITY_CHECK]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_QUANTITY_CHECK](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[PACKAGE_ID] [uniqueidentifier] NULL,
	[ESTIMATED_CARGO_PIECE] [int] NULL,
	[ACTUAL_CARGO_PIECE] [int] NULL,
	[SEQ] [int] NULL,
	[START_DATE] [datetime] NULL,
	[FINISH_DATE] [datetime] NULL,
	[JOB_STATUS] [char](1) NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_MENU]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_MENU](
	[MENU_ID] [nvarchar](100) NOT NULL,
	[PARENT_ID] [nvarchar](255) NULL,
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[MENU_NAME] [nvarchar](max) NOT NULL,
	[MENU_ICON] [nvarchar](255) NULL,
	[IS_VISIBLE] [bit] NOT NULL,
	[ORDER_BY] [int] NOT NULL,
	[VIEW_PAGE] [nvarchar](100) NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](500) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
 CONSTRAINT [PK_SA_MENU] PRIMARY KEY CLUSTERED 
(
	[MENU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_PERMISSION]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_PERMISSION](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[ROLE_CODE] [nvarchar](100) NOT NULL,
	[MENU_ID] [nvarchar](100) NOT NULL,
	[CAN_VIEW] [bit] NOT NULL,
	[CAN_ADD_NEW] [bit] NOT NULL,
	[CAN_MODIFY] [bit] NOT NULL,
	[CAN_DELETE] [bit] NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](500) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_ROLE]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_ROLE](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[ROLE_CODE] [nvarchar](100) NOT NULL,
	[ROLE_NAME] [nvarchar](500) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](500) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROLE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_USER]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_USER](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[USERNAME] [nvarchar](450) NOT NULL,
	[PASSWORD] [nvarchar](100) NULL,
	[ROLE_CODE] [nvarchar](100) NOT NULL,
	[FULLNAME] [nvarchar](max) NULL,
	[BIRTHDAY] [datetime] NULL,
	[ADDRESS] [nvarchar](max) NULL,
	[TELEPHONE] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](max) NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[REMARK] [nvarchar](max) NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](500) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [SA_USER_UNIQUE] UNIQUE NONCLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRF_CODES]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRF_CODES](
	[TRF_CODE] [nvarchar](12) NOT NULL,
	[TRF_DESC] [nvarchar](150) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](500) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TRF_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRF_DIS]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRF_DIS](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_CODE] [nvarchar](50) NOT NULL,
	[TRF_TEMP_CODE] [nvarchar](100) NOT NULL,
	[TRF_CODE] [nvarchar](12) NOT NULL,
	[TRF_DESC] [nvarchar](150) NULL,
	[AMT_CBM] [numeric](12, 2) NOT NULL,
	[VAT] [numeric](5, 2) NULL,
	[INCLUDE_VAT] [bit] NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](500) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRF_STD]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRF_STD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[TRF_TEMP_CODE] [nvarchar](100) NOT NULL,
	[TRF_CODE] [nvarchar](12) NOT NULL,
	[TRF_DESC] [nvarchar](150) NULL,
	[AMT_CBM] [numeric](12, 2) NOT NULL,
	[VAT] [numeric](5, 2) NULL,
	[INCLUDE_VAT] [bit] NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](500) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRF_TEMP]    Script Date: 8/27/2024 3:10:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRF_TEMP](
	[TRF_TEMP_CODE] [nvarchar](100) NOT NULL,
	[TRF_TEMP_NAME] [nvarchar](50) NOT NULL,
	[FROM_DATE] [datetime] NOT NULL,
	[TO_DATE] [datetime] NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.TRF_TEMP] PRIMARY KEY CLUSTERED 
(
	[TRF_TEMP_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BS_BLOCK] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[BS_BLOCK] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[BS_CELL] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_CELL] ADD  CONSTRAINT [DEFAULT_BS_CELL_STATUS]  DEFAULT ((0)) FOR [STATUS]
GO
ALTER TABLE [dbo].[BS_CELL] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[BS_CELL] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[BS_CUSTOMER] ADD  CONSTRAINT [DEFAULT_BS_CUSTOMER_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[BS_CUSTOMER] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[BS_CUSTOMER] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[BS_CUSTOMER_TYPE] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[BS_CUSTOMER_TYPE] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[BS_METHOD] ADD  CONSTRAINT [DEFAULT_BS_METHOD_IS_SERVICE]  DEFAULT ((0)) FOR [IS_SERVICE]
GO
ALTER TABLE [dbo].[BS_METHOD] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[BS_METHOD] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[BS_PACKAGE_UNIT] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[BS_PACKAGE_UNIT] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[BS_WAREHOUSE] ADD  DEFAULT ((0)) FOR [STATUS]
GO
ALTER TABLE [dbo].[BS_WAREHOUSE] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[BS_WAREHOUSE] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[CONFIG_ATTACH_SRV] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[CONFIG_ATTACH_SRV] ADD  CONSTRAINT [DEFAULT_CONFIG_ATTACH_SRV_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[CONFIG_ATTACH_SRV] ADD  CONSTRAINT [DEFAULT_CONFIG_ATTACH_SRV_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[DELIVER_ORDER] ADD  CONSTRAINT [DEFAULT_DELIVER_ORDER_JOB_CHK]  DEFAULT ((0)) FOR [JOB_CHK]
GO
ALTER TABLE [dbo].[DELIVER_ORDER] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[DELIVER_ORDER] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[DELIVER_ORDER] ADD  DEFAULT ((1)) FOR [IS_VALID]
GO
ALTER TABLE [dbo].[DELIVER_ORDER] ADD  DEFAULT ((1)) FOR [CAN_CANCEL]
GO
ALTER TABLE [dbo].[DELIVERY_ORDER_DETAIL] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DELIVERY_ORDER_DETAIL] ADD  CONSTRAINT [DEFAULT_DELIVERY_ORDER_DETAIL_QUANTITY_CHK]  DEFAULT ((0)) FOR [QUANTITY_CHK]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  CONSTRAINT [DEFAULT_DT_CNTR_MNF_LD_STATUSOFGOOD]  DEFAULT ((1)) FOR [STATUSOFGOOD]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] ADD  CONSTRAINT [DEFAULT_DT_PACKAGE_MNF_LD_JOB_TYPE ]  DEFAULT ('NK') FOR [JOB_TYPE ]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[DT_VESSEL_VISIT] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[DT_VESSEL_VISIT] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[INV_VAT] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[INV_VAT] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[INV_VAT_DTL] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[INV_VAT_DTL] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[INV_VAT_DTL] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  CONSTRAINT [DEFAULT_SA_MENU_ROWGUID]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  CONSTRAINT [DEFAULT_SA_MENU_IS_VISIBLE]  DEFAULT ((1)) FOR [IS_VISIBLE]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  CONSTRAINT [DEFAULT_SA_MENU_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  CONSTRAINT [DEFAULT_SA_MENU_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  CONSTRAINT [DEFAULT_SA_PERMISSION_ROWGUID]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  CONSTRAINT [DEFAULT_SA_PERMISSION_IS_VIEW]  DEFAULT ((0)) FOR [CAN_VIEW]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  CONSTRAINT [DEFAULT_SA_PERMISSION_IS_ADD_NEW]  DEFAULT ((0)) FOR [CAN_ADD_NEW]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  CONSTRAINT [DEFAULT_SA_PERMISSION_IS_MODIFY]  DEFAULT ((0)) FOR [CAN_MODIFY]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  CONSTRAINT [DEFAULT_SA_PERMISSION_IS_DELETE]  DEFAULT ((0)) FOR [CAN_DELETE]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  CONSTRAINT [DEFAULT_SA_PERMISSION_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  CONSTRAINT [DEFAULT_SA_PERMISSION_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[SA_ROLE] ADD  CONSTRAINT [DEFAULT_SA_ROLE_ROWGUID]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_ROLE] ADD  CONSTRAINT [DEFAULT_SA_ROLE_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[SA_ROLE] ADD  CONSTRAINT [DEFAULT_SA_ROLE_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[SA_USER] ADD  CONSTRAINT [DEFAULT_SA_USER_ROWGUID]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_USER] ADD  CONSTRAINT [DEFAULT_SA_USER_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[SA_USER] ADD  CONSTRAINT [DEFAULT_SA_USER_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[SA_USER] ADD  CONSTRAINT [DEFAULT_SA_USER_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[TRF_CODES] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[TRF_CODES] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[TRF_DIS] ADD  CONSTRAINT [DEFAULT_TRF_DIS_ROWGUID]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[TRF_DIS] ADD  CONSTRAINT [DEFAULT_TRF_DIS_INCLUDE_VAT]  DEFAULT ((1)) FOR [INCLUDE_VAT]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  CONSTRAINT [DEFAULT_TRF_STD_INCLUDE_VAT]  DEFAULT ((1)) FOR [INCLUDE_VAT]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  DEFAULT (getdate()) FOR [CREATED_AT]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  DEFAULT (getdate()) FOR [UPDATED_AT]
GO
ALTER TABLE [dbo].[BS_BLOCK]  WITH CHECK ADD  CONSTRAINT [FK_BS_BLOCK_BS_WAREHOUSE] FOREIGN KEY([WAREHOUSE_CODE])
REFERENCES [dbo].[BS_WAREHOUSE] ([WAREHOUSE_CODE])
GO
ALTER TABLE [dbo].[BS_BLOCK] CHECK CONSTRAINT [FK_BS_BLOCK_BS_WAREHOUSE]
GO
ALTER TABLE [dbo].[BS_CELL]  WITH CHECK ADD  CONSTRAINT [FK_BS_CELL_BS_BLOCK] FOREIGN KEY([BLOCK_CODE])
REFERENCES [dbo].[BS_BLOCK] ([BLOCK_CODE])
GO
ALTER TABLE [dbo].[BS_CELL] CHECK CONSTRAINT [FK_BS_CELL_BS_BLOCK]
GO
ALTER TABLE [dbo].[BS_CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_BS_CUSTOMER_BS_CUSTOMER_TYPE] FOREIGN KEY([CUSTOMER_TYPE_CODE])
REFERENCES [dbo].[BS_CUSTOMER_TYPE] ([CUSTOMER_TYPE_CODE])
GO
ALTER TABLE [dbo].[BS_CUSTOMER] CHECK CONSTRAINT [FK_BS_CUSTOMER_BS_CUSTOMER_TYPE]
GO
ALTER TABLE [dbo].[CONFIG_ATTACH_SRV]  WITH CHECK ADD  CONSTRAINT [FK_CONFIG_ATTACH_SRV_BS_METHOD] FOREIGN KEY([METHOD_CODE])
REFERENCES [dbo].[BS_METHOD] ([METHOD_CODE])
GO
ALTER TABLE [dbo].[CONFIG_ATTACH_SRV] CHECK CONSTRAINT [FK_CONFIG_ATTACH_SRV_BS_METHOD]
GO
ALTER TABLE [dbo].[DELIVER_ORDER]  WITH CHECK ADD  CONSTRAINT [DELIVER_ORDER_BS_CUSTOMER_FK] FOREIGN KEY([CUSTOMER_CODE])
REFERENCES [dbo].[BS_CUSTOMER] ([CUSTOMER_CODE])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DELIVER_ORDER] CHECK CONSTRAINT [DELIVER_ORDER_BS_CUSTOMER_FK]
GO
ALTER TABLE [dbo].[DELIVER_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_DELIVER_ORDER_DT_CNTR_MNF_LD_1] FOREIGN KEY([CONTAINER_ID])
REFERENCES [dbo].[DT_CNTR_MNF_LD] ([ROWGUID])
GO
ALTER TABLE [dbo].[DELIVER_ORDER] CHECK CONSTRAINT [FK_DELIVER_ORDER_DT_CNTR_MNF_LD_1]
GO
ALTER TABLE [dbo].[DELIVER_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_DELIVER_ORDER_DT_PACKAGE_MNF_LD_2] FOREIGN KEY([PACKAGE_ID])
REFERENCES [dbo].[DT_PACKAGE_MNF_LD] ([ROWGUID])
GO
ALTER TABLE [dbo].[DELIVER_ORDER] CHECK CONSTRAINT [FK_DELIVER_ORDER_DT_PACKAGE_MNF_LD_2]
GO
ALTER TABLE [dbo].[DELIVERY_ORDER_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERY_ORDER_DETAIL_BS_METHOD_1] FOREIGN KEY([METHOD_CODE])
REFERENCES [dbo].[BS_METHOD] ([METHOD_CODE])
GO
ALTER TABLE [dbo].[DELIVERY_ORDER_DETAIL] CHECK CONSTRAINT [FK_DELIVERY_ORDER_DETAIL_BS_METHOD_1]
GO
ALTER TABLE [dbo].[DELIVERY_ORDER_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERY_ORDER_DETAIL_DELIVER_ORDER] FOREIGN KEY([DE_ORDER_NO])
REFERENCES [dbo].[DELIVER_ORDER] ([DE_ORDER_NO])
GO
ALTER TABLE [dbo].[DELIVERY_ORDER_DETAIL] CHECK CONSTRAINT [FK_DELIVERY_ORDER_DETAIL_DELIVER_ORDER]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD]  WITH CHECK ADD  CONSTRAINT [FK_DT_CNTR_MNF_LD_BS_ITEM_TYPE_1] FOREIGN KEY([ITEM_TYPE_CODE])
REFERENCES [dbo].[BS_ITEM_TYPE] ([ITEM_TYPE_CODE])
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] CHECK CONSTRAINT [FK_DT_CNTR_MNF_LD_BS_ITEM_TYPE_1]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD]  WITH CHECK ADD  CONSTRAINT [FK_DT_CNTR_MNF_LD_DT_VESSEL_VISIT] FOREIGN KEY([VOYAGEKEY])
REFERENCES [dbo].[DT_VESSEL_VISIT] ([VOYAGEKEY])
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] CHECK CONSTRAINT [FK_DT_CNTR_MNF_LD_DT_VESSEL_VISIT]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_DT_PALLET_STOCK_BS_CELL_1] FOREIGN KEY([CELL_ID])
REFERENCES [dbo].[BS_CELL] ([ROWGUID])
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] CHECK CONSTRAINT [FK_DT_PALLET_STOCK_BS_CELL_1]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_DT_PALLET_STOCK_JOB_QUANTITY_CHECK] FOREIGN KEY([JOB_QUANTITY_ID])
REFERENCES [dbo].[JOB_QUANTITY_CHECK] ([ROWGUID])
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] CHECK CONSTRAINT [FK_DT_PALLET_STOCK_JOB_QUANTITY_CHECK]
GO
ALTER TABLE [dbo].[INV_VAT_DTL]  WITH CHECK ADD  CONSTRAINT [FK_INV_VAT_DTL_INV_VAT] FOREIGN KEY([INV_ID])
REFERENCES [dbo].[INV_VAT] ([INV_NO])
GO
ALTER TABLE [dbo].[INV_VAT_DTL] CHECK CONSTRAINT [FK_INV_VAT_DTL_INV_VAT]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK]  WITH CHECK ADD  CONSTRAINT [FK_JOB_QUANTITY_CHECK_DT_PACKAGE_MNF_LD] FOREIGN KEY([PACKAGE_ID])
REFERENCES [dbo].[DT_PACKAGE_MNF_LD] ([ROWGUID])
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] CHECK CONSTRAINT [FK_JOB_QUANTITY_CHECK_DT_PACKAGE_MNF_LD]
GO
ALTER TABLE [dbo].[SA_PERMISSION]  WITH CHECK ADD  CONSTRAINT [FK_SA_PERMISSION_SA_MENU] FOREIGN KEY([MENU_ID])
REFERENCES [dbo].[SA_MENU] ([MENU_ID])
GO
ALTER TABLE [dbo].[SA_PERMISSION] CHECK CONSTRAINT [FK_SA_PERMISSION_SA_MENU]
GO
ALTER TABLE [dbo].[SA_PERMISSION]  WITH CHECK ADD  CONSTRAINT [FK_SA_PERMISSION_SA_ROLE] FOREIGN KEY([ROLE_CODE])
REFERENCES [dbo].[SA_ROLE] ([ROLE_CODE])
GO
ALTER TABLE [dbo].[SA_PERMISSION] CHECK CONSTRAINT [FK_SA_PERMISSION_SA_ROLE]
GO
ALTER TABLE [dbo].[SA_USER]  WITH CHECK ADD  CONSTRAINT [FK_SA_USER_SA_ROLE] FOREIGN KEY([ROLE_CODE])
REFERENCES [dbo].[SA_ROLE] ([ROLE_CODE])
GO
ALTER TABLE [dbo].[SA_USER] CHECK CONSTRAINT [FK_SA_USER_SA_ROLE]
GO
ALTER TABLE [dbo].[TRF_DIS]  WITH CHECK ADD  CONSTRAINT [FK_DISCOUNT_TARIFF_BS_CUSTOMER_2] FOREIGN KEY([CUSTOMER_CODE])
REFERENCES [dbo].[BS_CUSTOMER] ([CUSTOMER_CODE])
GO
ALTER TABLE [dbo].[TRF_DIS] CHECK CONSTRAINT [FK_DISCOUNT_TARIFF_BS_CUSTOMER_2]
GO
ALTER TABLE [dbo].[TRF_DIS]  WITH CHECK ADD  CONSTRAINT [FK_DISCOUNT_TARIFF_BS_ITEM_TYPE] FOREIGN KEY([ITEM_TYPE_CODE])
REFERENCES [dbo].[BS_ITEM_TYPE] ([ITEM_TYPE_CODE])
GO
ALTER TABLE [dbo].[TRF_DIS] CHECK CONSTRAINT [FK_DISCOUNT_TARIFF_BS_ITEM_TYPE]
GO
ALTER TABLE [dbo].[TRF_DIS]  WITH CHECK ADD  CONSTRAINT [FK_DISCOUNT_TARIFF_BS_METHOD_1] FOREIGN KEY([METHOD_CODE])
REFERENCES [dbo].[BS_METHOD] ([METHOD_CODE])
GO
ALTER TABLE [dbo].[TRF_DIS] CHECK CONSTRAINT [FK_DISCOUNT_TARIFF_BS_METHOD_1]
GO
ALTER TABLE [dbo].[TRF_DIS]  WITH CHECK ADD  CONSTRAINT [FK_DISCOUNT_TARIFF_TRF_CODES] FOREIGN KEY([TRF_CODE])
REFERENCES [dbo].[TRF_CODES] ([TRF_CODE])
GO
ALTER TABLE [dbo].[TRF_DIS] CHECK CONSTRAINT [FK_DISCOUNT_TARIFF_TRF_CODES]
GO
ALTER TABLE [dbo].[TRF_DIS]  WITH CHECK ADD  CONSTRAINT [FK_DISCOUNT_TARIFF_TRF_TEMP_3] FOREIGN KEY([TRF_TEMP_CODE])
REFERENCES [dbo].[TRF_TEMP] ([TRF_TEMP_CODE])
GO
ALTER TABLE [dbo].[TRF_DIS] CHECK CONSTRAINT [FK_DISCOUNT_TARIFF_TRF_TEMP_3]
GO
ALTER TABLE [dbo].[TRF_STD]  WITH CHECK ADD  CONSTRAINT [FK_TRF_STD_BS_ITEM_TYPE] FOREIGN KEY([ITEM_TYPE_CODE])
REFERENCES [dbo].[BS_ITEM_TYPE] ([ITEM_TYPE_CODE])
GO
ALTER TABLE [dbo].[TRF_STD] CHECK CONSTRAINT [FK_TRF_STD_BS_ITEM_TYPE]
GO
ALTER TABLE [dbo].[TRF_STD]  WITH CHECK ADD  CONSTRAINT [FK_TRF_STD_BS_METHOD_1] FOREIGN KEY([METHOD_CODE])
REFERENCES [dbo].[BS_METHOD] ([METHOD_CODE])
GO
ALTER TABLE [dbo].[TRF_STD] CHECK CONSTRAINT [FK_TRF_STD_BS_METHOD_1]
GO
ALTER TABLE [dbo].[TRF_STD]  WITH CHECK ADD  CONSTRAINT [FK_TRF_STD_TRF_CODES_2] FOREIGN KEY([TRF_CODE])
REFERENCES [dbo].[TRF_CODES] ([TRF_CODE])
GO
ALTER TABLE [dbo].[TRF_STD] CHECK CONSTRAINT [FK_TRF_STD_TRF_CODES_2]
GO
ALTER TABLE [dbo].[TRF_STD]  WITH CHECK ADD  CONSTRAINT [FK_TRF_STD_TRF_TEMP_3] FOREIGN KEY([TRF_TEMP_CODE])
REFERENCES [dbo].[TRF_TEMP] ([TRF_TEMP_CODE])
GO
ALTER TABLE [dbo].[TRF_STD] CHECK CONSTRAINT [FK_TRF_STD_TRF_TEMP_3]
GO
